In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_excel('all_reviews.xlsx')

In [3]:
df

,№,Сеть / формат,Адрес точки,Источник,Текст отзыва,Оценка,Дата
0,1,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Удобный магазин, вкусный кофе и выпечка. Быстр...",5,18 октября 2025
1,2,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Доставили сюда посылку 5post, было указано что...",2,27 апреля
2,3,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Расположение удобное, продавцы улыбчивые, прия...",3,27 ноября 2025
3,4,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Нормальный магазин. Не очень большой выбор, но...",4,2 января
4,5,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,Кофе 3 в 1 80₽ и говорят такая цена. Через мес...,1,30 ноября 2025
...,...,...,...,...,...,...,...
252,253,Налету,Не указан,Habr,"Кажется, сегодня ту Пятерочку настиг хабраэффе...",Форум (без оценки),24 фев 2021
253,254,Налету,Не указан,Habr,"Где же мои глупые дети работать то будут, на п...",Форум (без оценки),1 мар 2021
254,255,Налету,Не указан,Habr,"Ну, что заголовок кликбэйтный, это понятно :)\...",Форум (без оценки),8 мар 2021
255,256,Налету,Не указан,Habr,Пользуюсь сервисом в одном из Зеленоградских П...,Форум (без оценки),5 мая 2021
256,257,Налету,Не указан,Habr,Говорить о внедрении технологии повсеместно па...,Форум (без оценки),19 апр 2023

In [ ]:
df['Адрес точки'] = df['Адрес точки'].replace('Не указан', np.nan)
df['Оценка'] = df['Оценка'].replace('Форум (без оценки)', np.nan)
df['Оценка'] = pd.to_numeric(df['Оценка'])

In [5]:
df['Город'] = df['Адрес точки'].str.split(',').str[0]

In [6]:
df

,№,Сеть / формат,Адрес точки,Источник,Текст отзыва,Оценка,Дата,Город
0,1,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Удобный магазин, вкусный кофе и выпечка. Быстр...",5.0,18 октября 2025,Москва
1,2,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Доставили сюда посылку 5post, было указано что...",2.0,27 апреля,Москва
2,3,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Расположение удобное, продавцы улыбчивые, прия...",3.0,27 ноября 2025,Москва
3,4,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Нормальный магазин. Не очень большой выбор, но...",4.0,2 января,Москва
4,5,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,Кофе 3 в 1 80₽ и говорят такая цена. Через мес...,1.0,30 ноября 2025,Москва
...,...,...,...,...,...,...,...,...
252,253,Налету,NaN,Habr,"Кажется, сегодня ту Пятерочку настиг хабраэффе...",NaN,24 фев 2021,NaN
253,254,Налету,NaN,Habr,"Где же мои глупые дети работать то будут, на п...",NaN,1 мар 2021,NaN
254,255,Налету,NaN,Habr,"Ну, что заголовок кликбэйтный, это понятно :)\...",NaN,8 мар 2021,NaN
255,256,Налету,NaN,Habr,Пользуюсь сервисом в одном из Зеленоградских П...,NaN,5 мая 2021,NaN
256,257,Налету,NaN,Habr,Говорить о внедрении технологии повсеместно па...,NaN,19 апр 2023,NaN

In [7]:
months = {
    'января': '01',
    'февраля': '02',
    'марта': '03',
    'апреля': '04',
    'мая': '05',
    'июня': '06',
    'июля': '07',
    'августа': '08',
    'сентября': '09',
    'октября': '10',
    'ноября': '11',
    'декабря': '12',

    'янв': '01',
    'фев': '02',
    'мар': '03',
    'апр': '04',
    'май': '05',
    'июн': '06',
    'июл': '07',
    'авг': '08',
    'сен': '09',
    'сент': '09',
    'окт': '10',
    'ноя': '11',
    'дек': '12'
}

def replace_dates(date):
    '''
    замена месяцев на цифры в столбце 
    '''
    date = str(date).lower()

    for month, numer in months.items():
        date = re.sub(rf'\b{month}\b', numer, date)

    return date

def add_year(date):
    date = str(date).lower().strip()

    if len(date.split()) == 2:
        date = date + ' 2026'

    return date

def drop_time(date):
    date = str(date).lower().strip()

    if ' в ' in date:
        date = date.split(' в ')[0]
        
    return date 

df['Дата'] = df['Дата'].apply(replace_dates)
df['Дата'] = df['Дата'].apply(add_year)
df['Дата'] = df['Дата'].apply(drop_time)

In [8]:
df['Дата'] = pd.to_datetime(df['Дата'], format='mixed', dayfirst=True)

In [9]:
df

,№,Сеть / формат,Адрес точки,Источник,Текст отзыва,Оценка,Дата,Город
0,1,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Удобный магазин, вкусный кофе и выпечка. Быстр...",5.0,2025-10-18,Москва
1,2,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Доставили сюда посылку 5post, было указано что...",2.0,2026-04-27,Москва
2,3,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Расположение удобное, продавцы улыбчивые, прия...",3.0,2025-11-27,Москва
3,4,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,"Нормальный магазин. Не очень большой выбор, но...",4.0,2026-01-02,Москва
4,5,Налету,"Москва, ул. Барклая, 6А, корп. 1",Yandex,Кофе 3 в 1 80₽ и говорят такая цена. Через мес...,1.0,2025-11-30,Москва
...,...,...,...,...,...,...,...,...
252,253,Налету,NaN,Habr,"Кажется, сегодня ту Пятерочку настиг хабраэффе...",NaN,2021-02-24,NaN
253,254,Налету,NaN,Habr,"Где же мои глупые дети работать то будут, на п...",NaN,2021-03-01,NaN
254,255,Налету,NaN,Habr,"Ну, что заголовок кликбэйтный, это понятно :)\...",NaN,2021-03-08,NaN
255,256,Налету,NaN,Habr,Пользуюсь сервисом в одном из Зеленоградских П...,NaN,2021-05-05,NaN
256,257,Налету,NaN,Habr,Говорить о внедрении технологии повсеместно па...,NaN,2023-04-19,NaN

In [10]:
df.to_excel('reviews_processed.xlsx', index=False)